### ISSUE TITLE
Should the absolute value of curv be used here?

### ISSUE THREAD

**Issue by vannaka** [GrappleRobotics/Pathfinder#10]
Should the absolute value of curv be used here?

https://github.com/GrappleRobotics/Pathfinder/blob/d7540ff0cd742de1d2f52d95316f088aac283a39/Pathfinder/src/include/grpl/model/coupled.h#L107

**Comment by JacisNonsense** [comment]
Yes, yes it should :P 
I should also get around to getting rid of the magic numbers while I'm at it
